# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b6d1488c5dc8ae550d13870b193a3da8d30db9763179259120e4922eb9c69fb2480a59d85c3f840b48dc5f5687d9827366baf6a616d46f33b28aec155848c2a

test:
  secret_key_base: 19250db09ffb41e78414461e3b0d136eec99607b057f6a450472ef9284cb5371df05c315098231126b5f9facb37b275a590ae3f479bcb250c7d4554e1f063404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
